# Generated by Django 6.0.3 on 2026-03-18 08:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_recruiter_and_job_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('is_experienced', models.BooleanField(default=False)),
                ('years_of_experience', models.CharField(blank=True, max_length=50)),
                ('previous_company', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], default='Applied', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='careeradvice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_max',
            field=models.PositiveIntegerField(default=99, help_text='Max years of experience'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_min',
            field=models.PositiveIntegerField(default=0, help_text='Min years of experience'),
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance & Banking'), ('Engineering', 'Engineering'), ('Sales', 'Sales & Marketing'), ('HR', 'Human Resources'), ('Education', 'Education'), ('Construction', 'Construction'), ('Hospitality', 'Hospitality & Tourism'), ('Logistics', 'Logistics & Supply Chain'), ('Manufacturing', 'Manufacturing'), ('Legal', 'Legal'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who posted this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, help_text='Max salary (monthly, USD)', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, help_text='Min salary (monthly, USD)', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin')], default='admin', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='core_job_status_38dcf0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['country', 'status'], name='core_job_country_fd253d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category', 'status'], name='core_job_categor_3fe6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['industry', 'status'], name='core_job_industr_479551_idx'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='CandidateProfile',
        ),
        migrations.DeleteModel(
            name='RecruiterProfile',
        ),
        migrations.DeleteModel(
            name='SavedJob',
        ),
    ]
